version: "3"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: squid
      POSTGRES_PASSWORD: postgres
    shm_size: 1gb
    ports:
      - "${DB_PORT}:5432"
      # command: ["postgres", "-c", "log_statement=all"]
#    volumes:
#      - ./data/db:/var/lib/postgresql/data

  indexer:
    build:
      context: .
      dockerfile: Dockerfile-indexer
    environment:
      - RPC_ENDPOINT=${RPC_ENDPOINT}
      - RATE_LIMIT=50
      - BATCH_SIZE=25
      - MIN_BLOCK_NUMBER=0
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=squid
      - DB_USER=postgres
      - DB_PASS=postgres
    depends_on:
      - db
    deploy:
      resources:
        limits:
          memory: 768M
        reservations:
          memory: 256M
    restart: unless-stopped

