name: Build and Deploy DNS

on:
  push:
    branches: [main, master]
    paths-ignore:
      - '.github/**'
      - '**.md'
    tags: ["v*"]
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: Target environment
        required: false
        options:
          - dev
          - stg
          - prod
      deploy_indexer:
        type: boolean
        description: Deploy indexer
        default: true
      deploy_explorer:
        type: boolean
        description: Deploy explorer
        default: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write
  packages: write
  actions: write
  id-token: write

jobs:
  deploy_indexer:
    uses: gear-ops/actions/.github/workflows/build-deploy.yaml@main
    with:
      argocd_server: ${{ vars.ARGOCD_SERVER }}
      vault_server: ${{ vars.VAULT_SERVER }}
      app: dns
      component: indexer
      env: ${{ inputs.env }}
      dockerfile: indexer/Dockerfile-indexer
      context: indexer
      paths_filter: |
        indexer/**
    secrets:
      WORKLOADS_REPO_TOKEN: ${{ secrets.WORKLOADS_REPO_TOKEN }}
      ARGOCD_TOKEN:         ${{ secrets.ARGOCD_TOKEN }}

  deploy_explorer:
    uses: gear-ops/actions/.github/workflows/build-deploy.yaml@main
    with:
      argocd_server: ${{ vars.ARGOCD_SERVER }}
      vault_server: ${{ vars.VAULT_SERVER }}
      app: dns
      component: explorer
      env: ${{ inputs.env }}
      dockerfile: api/Dockerfile
      context: api
      paths_filter: |
        api/**
    secrets:
      WORKLOADS_REPO_TOKEN: ${{ secrets.WORKLOADS_REPO_TOKEN }}
      ARGOCD_TOKEN:         ${{ secrets.ARGOCD_TOKEN }}
